### ISSUE TITLE
About the metrics reported in you paper.

### ISSUE THREAD

**Issue by chenerg** [alexrich021/3dvnet#2]
Very appreciate your great work! But I'm a bit confused about the metrics (like Acc in 3D Geometry) of NeuralRecon and Atlas reported in your paper. For example,

1. The metrics shown in NeuralRecon
![image](https://user-images.githubusercontent.com/24982715/144952219-19924900-480e-4db6-b243-a588acafc736.png)
2. The metrics shown in Atlas
![image](https://user-images.githubusercontent.com/24982715/144952288-a02606bf-610b-482d-833d-ef7a09029550.png)
2. The metrics shown in your paper 
![image](https://user-images.githubusercontent.com/24982715/144952326-09ea4fab-bec6-4f46-aa65-888286d1deea.png)

**Comment by alexrich021** [comment]
Hi there, thanks so much for your interest! I'm a bit confused what you are asking so I'll make a couple of comments on our results versus the results from NeuralRecon and Atlas and perhaps that will help.

First, in Sec. 2.4 of the [supplementary material](https://alexrich021.github.io/3dvnet/static/3dvnet_3dv2021_supplementary.pdf) we detail several choices in our evaluation pipeline that have a large positive effect on the Atlas metrics and a small positive effect on the NeuralRecon metrics. Namely, the choice of evaluating Atlas using a single-walled mesh while masking out regions of predicted reconstructions which are observed in camera frustums but not present in the ground truth reconstructions raises Atlas's F-score from 0.520 to 0.573.

Second, we observed in the mesh evaluation function used in Atlas ([here](https://github.com/magicleap/Atlas/blob/bee3ddbdb0935cf9aa9fc810e829115c6ab74dc5/atlas/evaluation.py#L79)), the Prec/Recal calculations appear to be switched. Notably, "dist1" is used for precision, but stores the distance from each ground truth vertex to the nearest predicted vertex. I would assume this means the Acc/Comp calculations are therefore switched, though I cannot be sure as they simply refer to these as "dist1" and "dist2" in that function. In our mesh evaluation function ([here](https://github.com/alexrich021/3dvnet/blob/f72e8a7ea890db4feae183b00347af6a1eff78d2/mv3d/eval/metricfunctions.py#L70)), we correct this. This likely explains why the reported Acc is consistent for both previous papers but different in our paper. We definitely welcome a second set of eyes on this though! These points are quite subtle and the more people that check them the better.

Hopefully that helps. If I didn't answer your question, feel free to re-phrase it and I will try again!

**Comment by chenerg** [comment]
Appreciate your answer and the details. That's very helpful for me. I will check these quantitative and meaningful details.
