### ISSUE TITLE
Data preprocess for ICL-NUIM and TUM-RGBD

### ISSUE THREAD

**Issue by DingYikang** [alexrich021/3dvnet#3]
Hi,
Thanks very much for your excellent work. I'm trying to test and re-train this work on ICL-NUIM and TUM-RGBD, but there is only instruction for scannet dataset in readme.txt. So I hope you can also give a simple instruction for data preprocess for ICL-NUIM and TUM-RGBD, which will help a lot.
Thanks again for your nice work!

**Comment by alexrich021** [comment]
Hi, thanks so much for your interest! 

The list of scenes for both datasets are in the [supplementary materials](https://alexrich021.github.io/3dvnet/static/3dvnet_3dv2021_supplementary.pdf) Sec. 2.3. Just download each set of scenes and put them in their own `icl-nuim_dir` and `tum-rgbd_dir` parent directories. Then the only things that need to be changed are in the `mv3d/config.py` and `mv3d/eval/config.py` files.

In `mv3d/config.py` change the `ICL_NUIM_DIR` and `TUM_RGBD_DIR` variables to point to the directories you created. Then you can run the pre-processing scripts found in `data_preprocess`.

In `mv3d/eval/config.py`, change the `SAVE_DIR` definition in the conditional to point to where you want to store evaluation results for those datasets. Then you can change the `DATASET_TYPE` variable to toggle between all datasets for evaluation.

That should be all you need to do to run evaluation of all methods. Note that we don't train on these datasets. They are quite small and  only used to show generalization to novel data distributions.

Also note we test using the "ICL-NUIM" dataset, which is different than the "Augmented ICL-NUIM" dataset. To make sure you've downloaded the correct scenes to reproduce our results, you can look at `mv3d/dsets/scenelists.py` and confirm the directory names of the scenes you downloaded match.

I also only set up the reconstruction visualizer in `mv3d/eval/visualizer.py` for ScanNet, but you can easily change this by modifying lines 9 and 26 to point to the `SAVE_DIR` and `ICL_NUIM_DIR`/ `TUM_RGBD_DIR` directories defined previously.

Hope this helps!

**Comment by DingYikang** [comment]
Thanks so much for your detailed reply! That helps a lot!
