### ISSUE TITLE
license information?

### ISSUE THREAD

**Issue by Rtakaha** [alexrich021/3dvnet#6]
Thank you very much for your great work!

I have one quick question. 
Are you willing to add license information to this repository? or should I consider this repo as [no license](https://choosealicense.com/no-permission/)?

Best regards,
Ryo

**Comment by alexrich021** [comment]
Hi Ryo, thanks for your interest!

That's a very valid concern. I can definitely upload license information. It might take me a little bit of time to upload though. You should consider this repository as open-source software.

Alex

**Comment by Rtakaha** [comment]
Okay! I consider this repo as open-source software, and will wait for the license to be uploaded.

Thank you again for your great work!
Ryo

**Comment by Rtakaha** [comment]
Hi Alex, 

I don't want to rush you, but is the license going to be uploaded soon?
I am happy to send a PR if it's not ready yet :).

If you don't have a clear view about license, I would recommend either Apache-2.0 or MIT license, as same as the baseline codes.

- [Apache-2.0](https://choosealicense.com/licenses/apache-2.0/)
  - [NeuralRecon](https://github.com/zju3dv/NeuralRecon)
  - [Atlas](https://github.com/magicleap/Atlas)
- [MIT](https://choosealicense.com/licenses/mit/)
  - [DeepVideoMVS](https://github.com/ardaduz/deep-video-mvs)
  - [Fast-MVSNet](https://github.com/svip-lab/FastMVSNet)
  - [GPMVS](https://github.com/AaltoML/GP-MVS) (you've already included in the directory)
  - [PointMVSNet](https://github.com/callmeray/PointMVSNet)

Thank you!
Ryo

**Comment by alexrich021** [comment]
Hey sorry for the delay on this. University of California has a process for open-sourcing software they recommend I use, I just haven't gotten to filling the forms out. If you would like, you can fork the repository and I can make a PR to your fork once I upload the license.

Please feel free to use my code before I upload a license. You have my permission as long as you treat it as open-source software. Don't worry about litigation from me - I'm just a PhD student focused on my dissertation.

Sorry again!
Alex

**Comment by Rtakaha** [comment]
Hi Alex, Thank you very much for the reply! I understand that you need to finish a process to officially open-source this repo.

I am sorry again for pushing you to work on this, but please understand I am in an environment where people are strict about license, and I need to make a move for that...

I will use your code as open-source software with gratitude while waiting for the license to be uploaded.

Thank you very much!
Ryo

**Comment by alexrich021** [comment]
I've added an MIT license. Additionally, I've added the proper licensing to the directories of each baseline method. Sorry again for the delay!

-Alex
